baseurl = "https://checklyhq.com"
languageCode = "en-us"
languageLang = "en"
title = "Checkly | Active Monitoring for Dev & Ops Teams"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[permalinks]
  blog = "/blog/:year/:month/:title/"

[params]
    description = "Checkly is the easiest way to actively monitor your API endpoints and browser click flows from a single dashboard"

[[menu.docs]]
	name = "API Checks"
	url = "/docs/api-checks/"
	weight = 20

[[menu.docs]]
	name = "Browser Checks"
	url = "/docs/browser-checks/"
	weight = 30

[[menu.docs]]
	name = "Alerting"
	url = "/docs/alerting/"
	weight = 40

[[menu.docs]]
	name = "TV-mode dashboards"
	url = "/docs/dashboards/"
	weight = 50

[[menu.docs]]
	name = "Teams"
	url = "/docs/teams/"
	weight = 50

[[menu.docs]]
	name = "Puppeteer Recorder"
	url = "/docs/puppeteer-recorder/"
	weight = 9999
