baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Checkly | Active Monitoring for Dev & Ops Teams"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
    description = "Checkly is the easiest way to monitor your browser click flows and API responses from a single dashboard"


[[menu.docs]]
	name = "API Checks"
	url = "/docs/api-checks/"
	weight = 10

[[menu.docs]]
	name = "Browser Checks"
	url = "/docs/browser-checks/"
	weight = 20
