baseurl = "https://checklyhq.com"
languageCode = "en-us"
languageLang = "en"
title = "API monitoring and Site Transaction Monitoring for DevOps Teams"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true

pygmentsCodeFences = true
pygmentsUseClasses = true

disqusShortname = "checkly"

[permalinks]
  blog = "/blog/:year/:month/:title/"

[params]
    description = "Monitor the performance and correctness of your API endpoints & vital site transactions from a single, simple dashboard"

[[menu.docs]]
	name = "Monitoring"
	url = "/docs/monitoring/"
	weight = 10


[[menu.docs]]
	name = "API Checks"
	url = "/docs/api-checks/"
	weight = 20

[[menu.docs]]
	name = "Browser Checks"
	url = "/docs/browser-checks/"
	weight = 30

[[menu.docs]]
	name = "Alerting"
	url = "/docs/alerting/"
	weight = 40

[[menu.docs]]
	name = "TV-mode dashboards"
	url = "/docs/dashboards/"
	weight = 50

[[menu.docs]]
	name = "Teams"
	url = "/docs/teams/"
	weight = 50

[[menu.docs]]
	name = "Integrations"
	url = "/docs/integrations/"
	weight = 60

[[menu.docs]]
	name = "Puppeteer Recorder"
	url = "/docs/puppeteer-recorder/"
	weight = 9999
